version: 4.0.{build}

image: Visual Studio 2019 Preview

pull_requests:
  do_not_increment_build_number: true

shallow_clone: true
clone_folder: C:\Projects\Victoria

only_commits:
  message: /Build/

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

before_build:
- cmd: dotnet restore

build:
  parallel: true
  verbosity: minimal

artifacts:
- path: '**\*.nupkg'
  name: TheMulti0.Victoria

deploy:
- provider: NuGet
  api_key:
    secure: /a4264N9m4XKnp7uRTTLxp0m8wqgzxHMYT1Oj1Nqr4EKn0iswdfuq+Rnp7NmHAJr
